#   ╭┄┄┄┄┅┅┅┅┅┄┄┄┄╮
#   »  Autostart  «
#   ╰┄┄┄┄┅┅┅┅┅┄┄┄┄╯

exec-once = vicinae server
exec-once = otd-daemon
exec-once = dunst
exec-once = awww-daemon
exec-once = zen-browser

exec-once = systemctl --user set-environment XDG_CURRENT_DESKTOP=wlroots; systemctl --user import-environment WAYLAND_DISPLAY; systemctl --user start xdg-desktop-portal-wlr.service
