#   ╭┄┄┄┄┄┅┅┅┅┄┄┄┄┄╮
#   »  Decoration  «
#   ╰┄┄┄┄┄┅┅┅┅┄┄┄┄┄╯

blur = 1
blur_optimized = 1
blur_params_radius = 3
blur_params_num_passes = 4
blur_params_noise = 0

shadows = 0

border_radius = 4
focused_opacity = 1.0
unfocused_opacity = 0.85

borderpx = 2
