#   ╭┄┄┄┅┅┅┄┄┄╮
#   »  Input  «
#   ╰┄┄┄┅┅┅┄┄┄╯

accel_profile = 0
accel_speed = -0.75

#   ╭┄┄┄┄┅┅┅┅┄┄┄┄╮
#   »  Keybinds  «
#   ╰┄┄┄┄┅┅┅┅┄┄┄┄╯

bind = Super, O, reload_config
bind = Super, C, killclient,

bind = Super + Shift, L, quit
bind = Super, L, spawn, hyprlock

bind = Super, Q, spawn, kitty
bind = Super, E, spawn, dolphin
bind = Super, space, spawn, vicinae toggle
bind = Super, R, spawn, rofi -show drun

bind = Super, F, togglefullscreen
bind = Super, T, togglefloating

bind = Super + Shift, S, spawn, hyprshot -m region --clipboard-only -s -z
bind = None, Print, spawn, hyprshot -m output --clipboard-only -s -z

bind = Alt + Shift, W, spawn, playerctl play-pause
bind = Alt + Shift, E, spawn, playerctl next
bind = Alt + Shift, Q, spawn, playerctl previous

bind = None, XF86AudioRaiseVolume, spawn, playerctl previous
bind = None, XF86AudioPlay,        spawn, playerctl play-pause
bind = None, XF86AudioLowerVolume, spawn, playerctl next

mousebind = Super, btn_left, moveresize, curmove
mousebind = Super, btn_right, moveresize, curresize

bind = Alt, Tab, focusstack, next
bind = Alt + Shift , Tab, focusstack, prev

bind = Super, Left, focusdir, left
bind = Super, Right, focusdir, right
bind = Super, Up, focusdir, up
bind = Super, Down, focusdir, down

bind = Super + Shift, 1, tag, 1, 0
bind = Super + Shift, 2, tag, 2, 0
bind = Super + Shift, 3, tag, 3, 0
bind = Super + Shift, 4, tag, 4, 0
bind = Super + Shift, 5, tag, 5, 0
bind = Super + Shift, 6, tag, 6, 0
bind = Super + Shift, 7, tag, 7, 0
bind = Super + Shift, 8, tag, 8, 0
bind = Super + Shift, 9, tag, 9, 0

bind = Super, 1, view, 1
bind = Super, 2, view, 2
bind = Super, 3, view, 3
bind = Super, 4, view, 4
bind = Super, 5, view, 5
bind = Super, 6, view, 6
bind = Super, 7, view, 7
bind = Super, 8, view, 8
bind = Super, 9, view, 9

bind = Super + Shift, Up, exchange_client, up
bind = Super + Shift, Down, exchange_client, down
bind = Super + Shift, Left, exchange_client, left
bind = Super + Shift, Right, exchange_client, right
