#   ╭┄┄┄┅┅┅┄┄┄╮
#   »  Rules  «
#   ╰┄┄┄┅┅┅┄┄┄╯

tagrule = id:1, layout_name: tile
tagrule = id:2, layout_name: tile
tagrule = id:3, layout_name: tile
tagrule = id:4, layout_name: tile
tagrule = id:5, layout_name: tile
tagrule = id:6, layout_name: tile
tagrule = id:7, layout_name: tile
tagrule = id:8, layout_name: tile
tagrule = id:9, layout_name: tile

windowrule = isfloating: 1, appid: com.saivert.pwvucontrol
windowrule = isfloating: 1, appid: org.gnome.Calculator
windowrule = isfloating: 1, appid: com.github.neithern.g4music

windowrule = isfloating: 1, isnoborder: 1, isnoradius: 1, isglobal: 1, isopensilent: 1, title: Picture-in-Picture
windowrule = tags: 2, appid: zen

sloppyfocus = 0
warpcursor = 1
drag_tile_to_tile = 1
enable_hotarea = 0

env = QT_QPA_PLATFORMTHEME, qt6ct
env = XDG_MENU_PREFIX, arch-
