    ###   ╔══════════════════════════╗   ###
    ###   𜲄   Hyprland Dotfiles v4   𜲄   ###
    ###   ╚══════════════════════════╝   ###

    source = hyprland/autostart.conf
    source = hyprland/environment.conf
    source = hyprland/decoration.conf
    source = hyprland/input.conf
    source = hyprland/keybinds.conf
    source = hyprland/keywords.conf
    source = hyprland/rules.conf

    #   ╔══════════╗
    #   𜲄  Output  𜲄
    #   ╚══════════╝

    monitor = HDMI-A-1, 1920x1080@180.00, auto, auto

    debug:disable_logs = false
