pragma Singleton
pragma ComponentBehavior: Bound
import QtQuick
import Quickshell

// Generated by matugen — do not edit manually
Singleton {
    id: root

    // Primary
    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color primaryOn: "{{colors.on_primary.default.hex}}"
    readonly property color primaryContainer: "{{colors.primary_container.default.hex}}"
    readonly property color primaryContainerOn: "{{colors.on_primary_container.default.hex}}"

    // Secondary
    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color secondaryOn: "{{colors.on_secondary.default.hex}}"
    readonly property color secondaryContainer: "{{colors.secondary_container.default.hex}}"
    readonly property color secondaryContainerOn: "{{colors.on_secondary_container.default.hex}}"

    // Tertiary
    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color tertiaryOn: "{{colors.on_tertiary.default.hex}}"
    readonly property color tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    readonly property color tertiaryContainerOn: "{{colors.on_tertiary_container.default.hex}}"

    // Error
    readonly property color error: "{{colors.error.default.hex}}"
    readonly property color errorOn: "{{colors.on_error.default.hex}}"
    readonly property color errorContainer: "{{colors.error_container.default.hex}}"
    readonly property color errorContainerOn: "{{colors.on_error_container.default.hex}}"

    // Surface
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color backgroundOn: "{{colors.on_background.default.hex}}"
    readonly property color surface: "{{colors.surface.default.hex}}"
    readonly property color surfaceOn: "{{colors.on_surface.default.hex}}"
    readonly property color surfaceVariant: "{{colors.surface_variant.default.hex}}"
    readonly property color surfaceVariantOn: "{{colors.on_surface_variant.default.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    readonly property color surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
    readonly property color surfaceContainerLowest: "{{colors.surface_container_lowest.default.hex}}"

    // Outline / misc
    readonly property color outline: "{{colors.outline.default.hex}}"
    readonly property color outlineVariant: "{{colors.outline_variant.default.hex}}"
    readonly property color inverseSurface: "{{colors.inverse_surface.default.hex}}"
    readonly property color inverseSurfaceOn: "{{colors.inverse_on_surface.default.hex}}"
    readonly property color inversePrimary: "{{colors.inverse_primary.default.hex}}"
    readonly property color shadow: "{{colors.shadow.default.hex}}"
    readonly property color scrim: "{{colors.scrim.default.hex}}"
}
