    ##   ╔═══════════════╗   ##
    ##   𜲄   Autostart   𜲄   ##
    ##   ╚═══════════════╝   ##

    exec-once = dunst
    exec-once = otd-daemon
    exec-once = vicinae server
    exec-once = zen-browser
    exec-once = $HOME/.config/hypr/scripts/eww.sh
    exec-once = discord --enable-features=UseOzonePlatform --ozone-platform=wayland
    exec-once = /usr/lib/polkit-kde-authentication-agent-1
