    ##   ╔═══════════════╗   ##
    ##   𜲄   Autostart   𜲄   ##
    ##   ╚═══════════════╝   ##

    exec-once = dunst
    exec-once = otd-daemon
    exec-once = vicinae server
    exec-once = zen-browser
    exec-once = $HOME/.config/hypr/scripts/eww.sh
#    exec-once = equibop --enable-features=UseOzonePlatform --ozone-platform=wayland
    exec-once = systemctl --user start hyprpolkitagent

    exec-once = qs
    exec-once = awww-daemon
