    source = keywords.conf

    ##   ╔══════════════╗   ##
    ##   𜲄   Keybinds   𜲄   ##
    ##   ╚══════════════╝   ##

    bind = $Modifier, Space, exec, $launcher
    bind = $Modifier, Q, exec, $terminal
    bind = $Modifier, L, exec, $SessionLock
    bind = $Modifier, E, exec, $fileManager
    bind = $Modifier, R, exec, rofi -show drun

    bind = $Modifier SHIFT, S, exec, hyprshot -m region --clipboard-only -s -z
    bind = , PRINT, exec, hyprshot -m output --clipboard-only -s -z

    bind = $Modifier, C, killactive,
    bind = $Modifier SHIFT, L, exit,
    bind = $Modifier, F, fullscreen, 0
    bind = $Modifier, T, togglefloating,
    bind = $Modifier, P, pseudo,                     # dwindle only
    bind = $Modifier, J, togglesplit,                # dwindle only

    bind = ALT SHIFT, W, exec, playerctl play-pause
    bind = ALT SHIFT, E, exec, playerctl next
    bind = ALT SHIFT, Q, exec, playerctl previous

    binde = , XF86AudioRaiseVolume, exec, playerctl previous
    binde = , XF86AudioPlay,        exec, playerctl play-pause
    binde = , XF86AudioLowerVolume, exec, playerctl next

    bind = ALT, TAB, cyclenext
    bind = $Modifier SHIFT, left, movewindow, l
    bind = $Modifier SHIFT, right, movewindow, r
    bind = $Modifier SHIFT, up, movewindow, u
    bind = $Modifier SHIFT, down, movewindow, d
    bind = $Modifier, left, movefocus, l
    bind = $Modifier, right, movefocus, r
    bind = $Modifier, up, movefocus, u
    bind = $Modifier, down, movefocus, d
    bind = $Modifier, mouse_up, workspace, e+1
    bind = $Modifier, mouse_down, workspace, e-1

    bindm = $Modifier, mouse:272, movewindow
    bindm = $Modifier, mouse:273, resizewindow

    bind = $Modifier, 1, workspace, 1
    bind = $Modifier, 2, workspace, 2
    bind = $Modifier, 3, workspace, 3
    bind = $Modifier, 4, workspace, 4
    bind = $Modifier, 5, workspace, 5
    bind = $Modifier, 6, workspace, 6
    bind = $Modifier, 7, workspace, 7
    bind = $Modifier, 8, workspace, 8
    bind = $Modifier, 9, workspace, 9
    bind = $Modifier, 0, workspace, 10
    bind = $Modifier SHIFT, 1, movetoworkspace, 1
    bind = $Modifier SHIFT, 2, movetoworkspace, 2
    bind = $Modifier SHIFT, 3, movetoworkspace, 3
    bind = $Modifier SHIFT, 4, movetoworkspace, 4
    bind = $Modifier SHIFT, 5, movetoworkspace, 5
    bind = $Modifier SHIFT, 6, movetoworkspace, 6
    bind = $Modifier SHIFT, 7, movetoworkspace, 7
    bind = $Modifier SHIFT, 8, movetoworkspace, 8
    bind = $Modifier SHIFT, 9, movetoworkspace, 9
    bind = $Modifier SHIFT, 0, movetoworkspace, 10
