    ##   ╔══════════════╗   ##
    ##   𜲄   Keywords   𜲄   ##
    ##   ╚══════════════╝   ##
    
    $browser = zen
    $launcher = vicinae toggle
    $fileManager = dolphin
    $terminal = kitty
    $SessionLock = hyprlock
    $Modifier = SUPER