    source = keywords.conf

    ##   ╔═══════════╗   ##
    ##   𜲄   Rules   𜲄   ##
    ##   ╚═══════════╝   ##

    windowrulev2 = workspace 2 silent, class:^(zen)$
    windowrulev2 = workspace 3 silent, class:^(equibop)$
    windowrulev2 = workspace 3 silent, class:^(discord)$
    windowrulev2 = workspace 1, class:^(zenlesszonezero.exe)$
    windowrulev2 = workspace 1, class:^(genshinimpact.exe)$
    windowrulev2 = workspace 1, class:^(starrail.exe)$
    windowrulev2 = workspace 1, class:^(osu!.exe)$

    windowrulev2 = fullscreen,class:^steam_app_\d+$

#    windowrulev2 = noscreenshare, class:^(equibop)$
    windowrulev2 = float, class:^(com.saivert.pwvucontrol)$
    windowrulev2 = float, class:^(org.gnome.Calculator)$
    windowrulev2 = float, class:^(com.github.neithern.g4music)$

    windowrulev2 = fullscreen, class:^(genshinimpact.exe)$
    windowrulev2 = fullscreen, class:^(Waydroid)$

    windowrule = suppressevent maximize, class:.*                                      # Ignore maximize Requests
    windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0 # XWayland drag fix

    # Zen Browser Picture-in-Picture

    $browserPiPtitle = ^(Picture-in-Picture)$
    windowrulev2 = float,      class:$browser, title:$browserPiPtitle
    windowrulev2 = pin,        class:$browser, title:$browserPiPtitle
    windowrulev2 = noborder,   class:$browser, title:$browserPiPtitle
    windowrulev2 = move 0 30%, class:$browser, title:$browserPiPtitle

    # Layer Rules
    layerrule = blur,       vicinae
    layerrule = blur,       nuno-shell
    layerrule = blur,       rofi
    layerrule = blur,       quickshell

    layerrule = ignorezero, quickshell
