    source = keywords.conf

    ##   ╔═══════════╗   ##
    ##   𜲄   Rules   𜲄   ##
    ##   ╚═══════════╝   ##

    windowrule = workspace 2 silent, match:class ^(zen)$
    windowrule = workspace 3 silent, match:class ^(equibop)$
    windowrule = workspace 3 silent, match:class ^(discord)$
    windowrule = workspace 1, match:class ^(zenlesszonezero.exe)$
    windowrule = workspace 1, fullscreen on, match:class ^(genshinimpact.exe)$
    windowrule = workspace 1, match:class ^(starrail.exe)$
    windowrule = workspace 1, match:class ^(osu!.exe)$

    windowrule = fullscreen on, match:class ^steam_app_\d+$

    windowrule = float on, match:class ^(com.saivert.pwvucontrol)$
    windowrule = float on, match:class ^(org.gnome.Calculator)$
    windowrule = float on, match:class ^(com.github.neithern.g4music)$

    windowrule = fullscreen on, match:class ^(Waydroid)$

    windowrule = suppress_event maximize, match:class .*                                      # Ignore maximize Requests
    windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0 # XWayland drag fix

# Firefox Picture-in-Picture // optimized for 16:9 videos because I hate the new windowrule revamp v6000

    windowrule = float on, pin on, border_size 0, move 0 300, size 600 337, match:title ^(Picture-in-Picture)$

# Layer Rules

    layerrule = blur on, match:namespace vicinae
    layerrule = blur on, match:namespace nuno-shell
    layerrule = blur on, match:namespace rofi
    layerrule = blur on, ignore_alpha 0, match:namespace quickshell
