##      __  ___                  _      _______
##     /  |/  /__ ____  ___ ____| | /| / / ___/
##    / /|_/ / _ `/ _ \/ _ `/ _ \ |/ |/ / /__
##   /_/  /_/\_,_/_//_/\_, /\___/__/|__/\___/
##                    /___/

source = ./conf/autostart.conf
source = ./conf/input.conf
source = ./conf/rules.conf
source = ./conf/decoration.conf

source = ./matugen.conf

#   ╭┄┄┄┅┅┅┅┄┄┄╮
#   »  Output  «
#   ╰┄┄┄┅┅┅┅┄┄┄╯

monitorrule = HDMI-A-1, 0.55, 1, tile, 0, 1, 0, 0, 1920, 1080, 180
